apiVersion: batch/v1
kind: Job
metadata:
  name: port-forward-job
  namespace: guestbook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: port-forward
        image: alpine:3.12
        command: ["/bin/sh", "-c"]
        args:
          - |
            #!/bin/sh
            NAMESPACE="guestbook"
            SERVICE_NAME="guestbook-ui"
            LOCAL_PORT=8080
            REMOTE_PORT=80

            # Function to establish port-forward
            port_forward() {
              kubectl port-forward svc/$SERVICE_NAME $LOCAL_PORT:$REMOTE_PORT -n $NAMESPACE
            }

            # Run port-forward in the background
            port_forward &

            # Capture the PID of the port-forward process
            PORT_FORWARD_PID=$!

            # Function to restart deployment and re-establish port-forward
            restart_and_forward() {
              kubectl rollout restart deployment/$SERVICE_NAME -n $NAMESPACE
              sleep 10  # Wait for the rollout to start
              kill $PORT_FORWARD_PID
              port_forward &
              PORT_FORWARD_PID=$!
            }

            # Call the function to restart and re-establish port-forward
            restart_and_forward
        # restartPolicy: OnFailure
